name: "Build"
on:
  pull_request:
  push:
    branches:
      - master
    tags:
    - '*'

jobs:
  build:
    strategy:
      matrix:
        build_image:
          - mcr.microsoft.com/dotnet/core/aspnet:3.1-bionic-arm64v8
          - mcr.microsoft.com/dotnet/core/aspnet:3.1-bionic-arm32v7
          - mcr.microsoft.com/dotnet/core/aspnet:3.1-bionic
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Build
      run: docker build --pull -f src/UdmApi.Proxy/Dockerfile --cache-from silvenga/unifi-udm-api-proxy:latest --build-arg BUILD_IMAGE=${{ matrix.build_image }} .

    - name: Publish (On Release Tags)
      uses: jerray/publish-docker-action@v1.0.4
      if: startsWith(github.ref, 'refs/tags/')
      with:
        file: src/UdmApi.Proxy/Dockerfile
        path: .
        build_args: BUILD_IMAGE=${{ matrix.build_image }}
        repository: silvenga/unifi-udm-api-proxy
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        auto_tag: true

    - name: Publish Latest (On Release Tags)
      uses: jerray/publish-docker-action@v1.0.4
      if: startsWith(github.ref, 'refs/tags/')
      with:
        file: src/UdmApi.Proxy/Dockerfile
        path: .
        build_args: BUILD_IMAGE=${{ matrix.build_image }}
        repository: silvenga/unifi-udm-api-proxy
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        tag: latest
