name: "Build"
on:
  pull_request:
  push:
    branches:
      - master
    tags:
    - '*'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Build
      run: docker build --pull -t silvenga/unifi-udm-api-proxy:latest -f src/UdmApi.Proxy/Dockerfile .

    - name: Publish (On Release Tags)
      uses: jerray/publish-docker-action@v1.0.3
      if: startsWith(github.ref, 'refs/tags/')
      with:
        file: src/UdmApi.Proxy/Dockerfile
        path: .
        repository: silvenga/unifi-udm-api-proxy
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        auto_tag: true
